services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node app.js
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
